#ifndef CALLTREECOLUMN_H
#define CALLTREECOLUMN_H

enum
{
    CALL_TREE_FUNCTION_COLUMN,
    CALL_TREE_SAMPLES_COLUMN,
    CALL_TREE_PERCENTAGE_COLUMN,
    CALL_TREE_SELF_SAMPLES_COLUMN,
    CALL_TREE_SELF_PERCENTAGE_COLUMN,
};

#endif // CALLTREECOLUMN_H
